### ISSUE TITLE
Should `validatorType` be obsolete?

### ISSUE THREAD

**Issue by mercmobily** [PolymerElements/iron-validator-behavior#21]
This element still has:

```
validatorType: {
    type: String,
    value: 'validator'
 },
```

However, Polymer.IronValidatableBehavior (the only consumer of this) considers `validatorType` "obsolete":

```
   /**
   * Namespace for this validator. This property is deprecated and should
   * not be used. For all intents and purposes, please consider it a
   * read-only, config-time property.
   */
  validatorType: {
    type: String,
    value: 'validator'
  }, 
```

And doesn't even use it, at all, in its code module:

```
registered: function() {
  Polymer.IronValidatableBehaviorMeta = new Polymer.IronMeta({type: 'validator'});
},
```

So, should this be made obsolete here too?

**Comment by notwaldorf** [comment]
Yup! (non-sarcastically: thanks for adding tracking issues, they will help a lot making sure we didn't miss anything)

**Comment by mercmobily** [comment]
OK :D I think it would be beneficial to update the comment/docs, so that people _know_ it's obsolete and it won't be a problem when it gets taken out!

**Comment by notwaldorf** [comment]
It's been removed in the 2.0-preview branch
